name: Push to input.txt

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update input.txt
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" | base64 --decode > token.txt
          echo "${{ github.event.inputs.user_input }}" >> input.txt
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add input.txt
          git commit -m "Add user input"
          git remote add origin-with-token "https://github.com/Antivenom03/wordbuild.git"
          git push --quiet origin-with-token main
