name: Push to input.txt

on:
  push:
    branches:
      - main

jobs:
  update-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Update input
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: node updateInput.js
