name: Push to input.txt

on:
  push:
    branches:
      - main

jobs:
  update-input:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Update input
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          sed -i '1s/^/\<p\>\<b\>From page:\<\/b\> '${{ github.event.head_commit.message }}'\<\/p\>\<p\>'${{ env.USER_INPUT }}'\<\/p\>/' input.html
          git add input.html
          git commit -m "Update input.html with new submission" -a
          git push
